const listaCanales = [
{ nombre: "HBO HD", url: "https://cointv.site/html/cvatt.html?get=SEJPSEQ=" },
{ nombre: "HBO2", url: "https://cointv.site/html/cvatt.html?get=SEJPXzI=" },
{ nombre: "HBo fa", url: "https://cointv.site/html/cvatt.html?get=SEJPX0ZhbWlseQ==" },
{ nombre: "Telef", url: "https://cointv.site/html/cvatt.html?get=VGVsZWZlSEQ=" },
{ nombre: "EsPn", url: "https://cointv.site/cvatt.html?get=RVNQTkhE&start=true" },
{ nombre: "FOXsports", url: "https://cointv.site/cvattde.html?get=Rm94U3BvcnRz" },
{ nombre: "Espn Prem", url: "https://cointv.site/html/cvattde.html?get=Rm94X1Nwb3J0c19QcmVtaXVuX0hE" },
{ nombre: "Espn Prem2", url: "https://nebunexa.life/tok.html?get=Rm94X1Nwb3J0c19QcmVtaXVuX0hE" },
{ nombre: "TNT S prem", url: "https://cointv.site/html/cvattde.html?get=VE5UX1Nwb3J0c19IRA" },
{ nombre: "tyc", url: "https://cointv.site/html/cvattde.html?get=VHlDU3BvcnQ" },
{ nombre: "Disco World", url: "https://cointv.site/html/cvatt.html?get=RGlzY292ZXJ5X1dvcmxkX0hE" },
{ nombre: "national g", url: "https://cointv.site/html/cvatt.html?get=TmF0R2VvSEQ=" },
{ nombre: "Garage TV", url: "https://stream1.sersat.com/hls/garagetv.m3u8" },
{ nombre: "UNITV Villa Maria", url: "https://vivo.solumedia.com:19360/uniteve/uniteve.m3u8" },
{ nombre: "CH 15 Cine", url: "https://stmv4.voxtvhd.com.br/canal5pueblo/canal5pueblo/playlist.m3u8" },
{ nombre: "NEOTV Cine", url: "https://videostream.shockmedia.com.ar:19360/neotvdigital/neotvdigital.m3u8" },
{ nombre: "Locomotion", url: "http://51.222.85.85:81/hls/loco/index.m3u8" },
{ nombre: "paka-paka", url: "https://cointv.site/cvatt.html?get=UEFLQV9QQUtB" },
{ nombre: "TNT", url: "https://cointv.site/cvatt.html?get=VE5UX0hEX0FyZw" },
{ nombre: "Animalplanet", url: "https://cointv.site/cvatt.html?get=QW5pbWFsUGxhbmV0" },
{ nombre: "History", url: "https://cointv.site/cvatt.html?get=SGlzdG9yeUhE" },
{ nombre: "CH Junin", url: "https://videostream.shockmedia.com.ar:19360/telejunin/telejunin.m3u8" },
{ nombre: "CH Peli 1", url: "https://run-rt-mx.otteravision.com/run/rt_mx/rt_mx.m3u8" },
{ nombre: "CH Peli acción", url: "https://run-rt-ac.otteravision.com/run/rt_ac/rt_ac.m3u8" },
{ nombre: "CH Peli terror", url: "https://run-ruthr.otteravision.com/run/ruthr/ruthr.m3u8" },
{ nombre: "CH Peli 2", url: "https://run-rucrl.otteravision.com/run/rucrl/rucrl.m3u8" },
{ nombre: "AMC", url: "https://amc-amcespanol-1-us.plex.wurl.tv/playlist.m3u8" },
{ nombre: "KANADE TV", url: "https://static.kanade.cl/hls/kanade.m3u8" },
{ nombre: "CH Peli 3", url: "https://stmv6.voxtvhd.com.br/cineaccion/cineaccion/playlist.m3u8" },
{ nombre: "3", url: "" },
{ nombre: "2", url: "" },
{ nombre: "3", url: "" },
{ nombre: "2", url: "" },
{ nombre: "3", url: "" },
];
