const digi = {
  "Serie A": {
"Temporada 1": [
      { url: "https://archive.org/download/digimon-adventure-latino/Digimon%20Adventure%20-%20S01E01.mp4", title: "Episodio 1" },
      { url: "https://archive.org/download/digimon-adventure-latino/Digimon%20Adventure%20-%20S01E02.mp4", title: "Episodio 2" },
      { url: "https://archive.org/download/digimon-adventure-latino/Digimon%20Adventure%20-%20S01E03.mp4", title: "Episodio 3" },
      { url: "https://archive.org/download/digimon-adventure-latino/Digimon%20Adventure%20-%20S01E04.mp4", title: "Episodio 3" },
      { url: "https://archive.org/download/digimon-adventure-latino/Digimon%20Adventure%20-%20S01E05.mp4", title: "Episodio 3" },
      { url: "https://archive.org/download/digimon-adventure-latino/Digimon%20Adventure%20-%20S01E06.mp4", title: "Episodio 3" },
      { url: "https://archive.org/download/digimon-adventure-latino/Digimon%20Adventure%20-%20S01E07.mp4", title: "Episodio 3" },
      { url: "https://archive.org/download/digimon-adventure-latino/Digimon%20Adventure%20-%20S01E08.mp4", title: "Episodio 3" },
      { url: "https://archive.org/download/digimon-adventure-latino/Digimon%20Adventure%20-%20S01E09.mp4", title: "Episodio 3" },
      { url: "https://archive.org/download/digimon-adventure-latino/Digimon%20Adventure%20-%20S01E10.mp4", title: "Episodio 3" },
      { url: "https://archive.org/download/digimon-adventure-latino/Digimon%20Adventure%20-%20S01E11.mp4", title: "Episodio 3" },
      { url: "https://archive.org/download/digimon-adventure-latino/Digimon%20Adventure%20-%20S01E12.mp4", title: "Episodio 3" },
      { url: "https://archive.org/download/digimon-adventure-latino/Digimon%20Adventure%20-%20S01E13.mp4", title: "Episodio 3" },
      { url: "https://archive.org/download/digimon-adventure-latino/Digimon%20Adventure%20-%20S01E14.mp4", title: "Episodio 3" },
      { url: "https://archive.org/download/digimon-adventure-latino/Digimon%20Adventure%20-%20S01E15.mp4", title: "Episodio 3" },
      { url: "https://archive.org/download/digimon-adventure-latino/Digimon%20Adventure%20-%20S01E16.mp4", title: "Episodio 3" },
      { url: "https://archive.org/download/digimon-adventure-latino/Digimon%20Adventure%20-%20S01E17.mp4", title: "Episodio 3" },
      { url: "https://archive.org/download/digimon-adventure-latino/Digimon%20Adventure%20-%20S01E18.mp4", title: "Episodio 3" },
      { url: "https://archive.org/download/digimon-adventure-latino/Digimon%20Adventure%20-%20S01E19.mp4", title: "Episodio 3" },
      { url: "https://archive.org/download/digimon-adventure-latino/Digimon%20Adventure%20-%20S01E20.mp4", title: "Episodio 3" },
      { url: "https://archive.org/download/digimon-adventure-latino/Digimon%20Adventure%20-%20S01E21.mp4", title: "Episodio 3" },
      { url: "https://archive.org/download/digimon-adventure-latino/Digimon%20Adventure%20-%20S01E22.mp4", title: "Episodio 3" },
      { url: "https://archive.org/download/digimon-adventure-latino/Digimon%20Adventure%20-%20S01E23.mp4", title: "Episodio 3" },
      { url: "https://archive.org/download/digimon-adventure-latino/Digimon%20Adventure%20-%20S01E24.mp4", title: "Episodio 3" },
      { url: "https://archive.org/download/digimon-adventure-latino/Digimon%20Adventure%20-%20S01E25.mp4", title: "Episodio 3" },
      { url: "https://archive.org/download/digimon-adventure-latino/Digimon%20Adventure%20-%20S01E26.mp4", title: "Episodio 3" },
      { url: "https://archive.org/download/digimon-adventure-latino/Digimon%20Adventure%20-%20S01E27.mp4", title: "Episodio 3" },
      { url: "https://archive.org/download/digimon-adventure-latino/Digimon%20Adventure%20-%20S01E28.mp4", title: "Episodio 3" },
      { url: "https://archive.org/download/digimon-adventure-latino/Digimon%20Adventure%20-%20S01E29.mp4", title: "Episodio 3" },
      { url: "https://archive.org/download/digimon-adventure-latino/Digimon%20Adventure%20-%20S01E30.mp4", title: "Episodio 3" },
      { url: "https://archive.org/download/digimon-adventure-latino/Digimon%20Adventure%20-%20S01E31.mp4", title: "Episodio 3" },
      { url: "https://archive.org/download/digimon-adventure-latino/Digimon%20Adventure%20-%20S01E32.mp4", title: "Episodio 3" },
      { url: "https://archive.org/download/digimon-adventure-latino/Digimon%20Adventure%20-%20S01E33.mp4", title: "Episodio 3" },
      { url: "https://archive.org/download/digimon-adventure-latino/Digimon%20Adventure%20-%20S01E34.mp4", title: "Episodio 3" },
      { url: "https://archive.org/download/digimon-adventure-latino/Digimon%20Adventure%20-%20S01E35.mp4", title: "Episodio 3" },
      { url: "https://archive.org/download/digimon-adventure-latino/Digimon%20Adventure%20-%20S01E36.mp4", title: "Episodio 3" },
      { url: "https://archive.org/download/digimon-adventure-latino/Digimon%20Adventure%20-%20S01E37.mp4", title: "Episodio 3" },
      { url: "https://archive.org/download/digimon-adventure-latino/Digimon%20Adventure%20-%20S01E38.mp4", title: "Episodio 3" },
      { url: "https://archive.org/download/digimon-adventure-latino/Digimon%20Adventure%20-%20S01E39.mp4", title: "Episodio 3" },
      { url: "https://archive.org/download/digimon-adventure-latino/Digimon%20Adventure%20-%20S01E40.mp4", title: "Episodio 3" },
      { url: "https://archive.org/download/digimon-adventure-latino/Digimon%20Adventure%20-%20S01E41.mp4", title: "Episodio 3" },
      { url: "https://archive.org/download/digimon-adventure-latino/Digimon%20Adventure%20-%20S01E42.mp4", title: "Episodio 3" },
      { url: "https://archive.org/download/digimon-adventure-latino/Digimon%20Adventure%20-%20S01E43.mp4", title: "Episodio 3" },
      { url: "https://archive.org/download/digimon-adventure-latino/Digimon%20Adventure%20-%20S01E44.mp4", title: "Episodio 3" },
      { url: "https://archive.org/download/digimon-adventure-latino/Digimon%20Adventure%20-%20S01E45.mp4", title: "Episodio 3" },
      { url: "https://archive.org/download/digimon-adventure-latino/Digimon%20Adventure%20-%20S01E46.mp4", title: "Episodio 3" },
      { url: "https://archive.org/download/digimon-adventure-latino/Digimon%20Adventure%20-%20S01E47.mp4", title: "Episodio 3" },
      { url: "https://archive.org/download/digimon-adventure-latino/Digimon%20Adventure%20-%20S01E48.mp4", title: "Episodio 3" },
      { url: "https://archive.org/download/digimon-adventure-latino/Digimon%20Adventure%20-%20S01E49.mp4", title: "Episodio 3" },
      { url: "https://archive.org/download/digimon-adventure-latino/Digimon%20Adventure%20-%20S01E50.mp4", title: "Episodio 3" },
      { url: "https://archive.org/download/digimon-adventure-latino/Digimon%20Adventure%20-%20S01E51.mp4", title: "Episodio 3" },
      { url: "https://archive.org/download/digimon-adventure-latino/Digimon%20Adventure%20-%20S01E52.mp4", title: "Episodio 3" }
    ],
    "Temporada 2": [
      { url: "https://archive.org/download/digimon-adventure-latino/Digimon%20Adventure%20-%20S01E01.mp4", title: "Episodio 1" },
      { url: "https://archive.org/download/digimon-adventure-latino/Digimon%20Adventure%20-%20S01E02.mp4", title: "Episodio 2" },
      { url: "https://archive.org/download/digimon-adventure-latino/Digimon%20Adventure%20-%20S01E03.mp4", title: "Episodio 3" }
    ]
    }
};
