const digi = {
  "Serie A": {
"Temporada 1": [
      { url: "https://archive.org/download/digimon-adventure-latino/Digimon%20Adventure%20-%20S01E01.mp4", title: "Episodio 1" },
      { url: "https://archive.org/download/digimon-adventure-latino/Digimon%20Adventure%20-%20S01E02.mp4", title: "Episodio 2" },
      { url: "https://archive.org/download/digimon-adventure-latino/Digimon%20Adventure%20-%20S01E03.mp4", title: "Episodio 3" },
      { url: "https://archive.org/download/digimon-adventure-latino/Digimon%20Adventure%20-%20S01E04.mp4", title: "Episodio 4" },
      { url: "https://archive.org/download/digimon-adventure-latino/Digimon%20Adventure%20-%20S01E05.mp4", title: "Episodio 5" },
      { url: "https://archive.org/download/digimon-adventure-latino/Digimon%20Adventure%20-%20S01E06.mp4", title: "Episodio 6" },
      { url: "https://archive.org/download/digimon-adventure-latino/Digimon%20Adventure%20-%20S01E07.mp4", title: "Episodio 7" },
      { url: "https://archive.org/download/digimon-adventure-latino/Digimon%20Adventure%20-%20S01E08.mp4", title: "Episodio 8" },
      { url: "https://archive.org/download/digimon-adventure-latino/Digimon%20Adventure%20-%20S01E09.mp4", title: "Episodio 9" },
      { url: "https://archive.org/download/digimon-adventure-latino/Digimon%20Adventure%20-%20S01E10.mp4", title: "Episodio 10" },
      { url: "https://archive.org/download/digimon-adventure-latino/Digimon%20Adventure%20-%20S01E11.mp4", title: "Episodio 11" },
      { url: "https://archive.org/download/digimon-adventure-latino/Digimon%20Adventure%20-%20S01E12.mp4", title: "Episodio 12" },
      { url: "https://archive.org/download/digimon-adventure-latino/Digimon%20Adventure%20-%20S01E13.mp4", title: "Episodio 13" },
      { url: "https://archive.org/download/digimon-adventure-latino/Digimon%20Adventure%20-%20S01E14.mp4", title: "Episodio 14" },
      { url: "https://archive.org/download/digimon-adventure-latino/Digimon%20Adventure%20-%20S01E15.mp4", title: "Episodio 15" },
      { url: "https://archive.org/download/digimon-adventure-latino/Digimon%20Adventure%20-%20S01E16.mp4", title: "Episodio 16" },
      { url: "https://archive.org/download/digimon-adventure-latino/Digimon%20Adventure%20-%20S01E17.mp4", title: "Episodio 17" },
      { url: "https://archive.org/download/digimon-adventure-latino/Digimon%20Adventure%20-%20S01E18.mp4", title: "Episodio 18" },
      { url: "https://archive.org/download/digimon-adventure-latino/Digimon%20Adventure%20-%20S01E19.mp4", title: "Episodio 19" },
      { url: "https://archive.org/download/digimon-adventure-latino/Digimon%20Adventure%20-%20S01E20.mp4", title: "Episodio 20" },
      { url: "https://archive.org/download/digimon-adventure-latino/Digimon%20Adventure%20-%20S01E21.mp4", title: "Episodio 21" },
      { url: "https://archive.org/download/digimon-adventure-latino/Digimon%20Adventure%20-%20S01E22.mp4", title: "Episodio 22" },
      { url: "https://archive.org/download/digimon-adventure-latino/Digimon%20Adventure%20-%20S01E23.mp4", title: "Episodio 23" },
      { url: "https://archive.org/download/digimon-adventure-latino/Digimon%20Adventure%20-%20S01E24.mp4", title: "Episodio 24" },
      { url: "https://archive.org/download/digimon-adventure-latino/Digimon%20Adventure%20-%20S01E25.mp4", title: "Episodio 25" },
      { url: "https://archive.org/download/digimon-adventure-latino/Digimon%20Adventure%20-%20S01E26.mp4", title: "Episodio 26" },
      { url: "https://archive.org/download/digimon-adventure-latino/Digimon%20Adventure%20-%20S01E27.mp4", title: "Episodio 27" },
      { url: "https://archive.org/download/digimon-adventure-latino/Digimon%20Adventure%20-%20S01E28.mp4", title: "Episodio 28" },
      { url: "https://archive.org/download/digimon-adventure-latino/Digimon%20Adventure%20-%20S01E29.mp4", title: "Episodio 29" },
      { url: "https://archive.org/download/digimon-adventure-latino/Digimon%20Adventure%20-%20S01E30.mp4", title: "Episodio 30" },
      { url: "https://archive.org/download/digimon-adventure-latino/Digimon%20Adventure%20-%20S01E31.mp4", title: "Episodio 31" },
      { url: "https://archive.org/download/digimon-adventure-latino/Digimon%20Adventure%20-%20S01E32.mp4", title: "Episodio 32" },
      { url: "https://archive.org/download/digimon-adventure-latino/Digimon%20Adventure%20-%20S01E33.mp4", title: "Episodio 33" },
      { url: "https://archive.org/download/digimon-adventure-latino/Digimon%20Adventure%20-%20S01E34.mp4", title: "Episodio 34" },
      { url: "https://archive.org/download/digimon-adventure-latino/Digimon%20Adventure%20-%20S01E35.mp4", title: "Episodio 35" },
      { url: "https://archive.org/download/digimon-adventure-latino/Digimon%20Adventure%20-%20S01E36.mp4", title: "Episodio 36" },
      { url: "https://archive.org/download/digimon-adventure-latino/Digimon%20Adventure%20-%20S01E37.mp4", title: "Episodio 37" },
      { url: "https://archive.org/download/digimon-adventure-latino/Digimon%20Adventure%20-%20S01E38.mp4", title: "Episodio 38" },
      { url: "https://archive.org/download/digimon-adventure-latino/Digimon%20Adventure%20-%20S01E39.mp4", title: "Episodio 39" },
      { url: "https://archive.org/download/digimon-adventure-latino/Digimon%20Adventure%20-%20S01E40.mp4", title: "Episodio 40" },
      { url: "https://archive.org/download/digimon-adventure-latino/Digimon%20Adventure%20-%20S01E41.mp4", title: "Episodio 41" },
      { url: "https://archive.org/download/digimon-adventure-latino/Digimon%20Adventure%20-%20S01E42.mp4", title: "Episodio 42" },
      { url: "https://archive.org/download/digimon-adventure-latino/Digimon%20Adventure%20-%20S01E43.mp4", title: "Episodio 43" },
      { url: "https://archive.org/download/digimon-adventure-latino/Digimon%20Adventure%20-%20S01E44.mp4", title: "Episodio 44" },
      { url: "https://archive.org/download/digimon-adventure-latino/Digimon%20Adventure%20-%20S01E45.mp4", title: "Episodio 45" },
      { url: "https://archive.org/download/digimon-adventure-latino/Digimon%20Adventure%20-%20S01E46.mp4", title: "Episodio 46" },
      { url: "https://archive.org/download/digimon-adventure-latino/Digimon%20Adventure%20-%20S01E47.mp4", title: "Episodio 47" },
      { url: "https://archive.org/download/digimon-adventure-latino/Digimon%20Adventure%20-%20S01E48.mp4", title: "Episodio 48" },
      { url: "https://archive.org/download/digimon-adventure-latino/Digimon%20Adventure%20-%20S01E49.mp4", title: "Episodio 49" },
      { url: "https://archive.org/download/digimon-adventure-latino/Digimon%20Adventure%20-%20S01E50.mp4", title: "Episodio 50" },
      { url: "https://archive.org/download/digimon-adventure-latino/Digimon%20Adventure%20-%20S01E51.mp4", title: "Episodio 51" },
      { url: "https://archive.org/download/digimon-adventure-latino/Digimon%20Adventure%20-%20S01E52.mp4", title: "Episodio 52" }
    ],
    "Temporada 2": [
      { url: "https://archive.org/download/digimon-adventure-latino/Digimon%20Adventure%20-%20S01E01.mp4", title: "Episodio 1" },
      { url: "https://archive.org/download/digimon-adventure-latino/Digimon%20Adventure%20-%20S01E02.mp4", title: "Episodio 2" },
      { url: "https://archive.org/download/digimon-adventure-latino/Digimon%20Adventure%20-%20S01E03.mp4", title: "Episodio 3" }
    ]
    }
};
