const dino = {
  "Serie A": {
"Temporada 1": [
      { url: "https://archive.org/download/digimon-adventure-latino/Digimon%20Adventure%20-%20S01E01.mp4", title: "Episodio 1" },
      { url: "https://archive.org/download/digimon-adventure-latino/Digimon%20Adventure%20-%20S01E02.mp4", title: "Episodio 2" },
      { url: "https://archive.org/download/digimon-adventure-latino/Digimon%20Adventure%20-%20S01E03.mp4", title: "Episodio 3" },
      { url: "https://archive.org/download/digimon-adventure-latino/Digimon%20Adventure%20-%20S01E04.mp4", title: "Episodio 3" },
      { url: "https://archive.org/download/digimon-adventure-latino/Digimon%20Adventure%20-%20S01E05.mp4", title: "Episodio 3" },
      { url: "https://archive.org/download/digimon-adventure-latino/Digimon%20Adventure%20-%20S01E06.mp4", title: "Episodio 3" },
      { url: "https://archive.org/download/digimon-adventure-latino/Digimon%20Adventure%20-%20S01E07.mp4", title: "Episodio 3" },
      { url: "https://archive.org/download/digimon-adventure-latino/Digimon%20Adventure%20-%20S01E08.mp4", title: "Episodio 3" },
      { url: "https://archive.org/download/digimon-adventure-latino/Digimon%20Adventure%20-%20S01E09.mp4", title: "Episodio 3" },
      { url: "https://archive.org/download/digimon-adventure-latino/Digimon%20Adventure%20-%20S01E10.mp4", title: "Episodio 3" },
      { url: "https://archive.org/download/digimon-adventure-latino/Digimon%20Adventure%20-%20S01E11.mp4", title: "Episodio 3" },
      { url: "https://archive.org/download/digimon-adventure-latino/Digimon%20Adventure%20-%20S01E12.mp4", title: "Episodio 3" },
      { url: "", title: "Episodio 3" },
      { url: "", title: "Episodio 3" },
      { url: "", title: "Episodio 3" },
      { url: "", title: "Episodio 3" },
      { url: "", title: "Episodio 3" },
      { url: "", title: "Episodio 3" },
      { url: "", title: "Episodio 3" },
      { url: "", title: "Episodio 3" },
      { url: "", title: "Episodio 3" },
      { url: "", title: "Episodio 3" },
      { url: "", title: "Episodio 3" },
      { url: "", title: "Episodio 3" },
      { url: "", title: "Episodio 3" },
      { url: "", title: "Episodio 3" },
      { url: "", title: "Episodio 3" },
      { url: "https://tu-servidor.com/dino/s1e3.mp4", title: "Episodio 3" },
      { url: "https://tu-servidor.com/dino/s1e3.mp4", title: "Episodio 3" },
      { url: "https://tu-servidor.com/dino/s1e3.mp4", title: "Episodio 3" },
      { url: "https://tu-servidor.com/dino/s1e3.mp4", title: "Episodio 3" },
      { url: "https://tu-servidor.com/dino/s1e3.mp4", title: "Episodio 3" },
      { url: "https://tu-servidor.com/dino/s1e3.mp4", title: "Episodio 3" },
      { url: "https://tu-servidor.com/dino/s1e3.mp4", title: "Episodio 3" },
      { url: "https://tu-servidor.com/dino/s1e3.mp4", title: "Episodio 3" },
      { url: "https://tu-servidor.com/dino/s1e3.mp4", title: "Episodio 3" },
      { url: "https://tu-servidor.com/dino/s1e3.mp4", title: "Episodio 3" },
      { url: "https://tu-servidor.com/dino/s1e3.mp4", title: "Episodio 3" },
      { url: "https://tu-servidor.com/dino/s1e3.mp4", title: "Episodio 3" },
      { url: "https://tu-servidor.com/dino/s1e3.mp4", title: "Episodio 3" },
      { url: "https://tu-servidor.com/dino/s1e3.mp4", title: "Episodio 3" },
      { url: "https://tu-servidor.com/dino/s1e3.mp4", title: "Episodio 3" },
      { url: "https://tu-servidor.com/dino/s1e3.mp4", title: "Episodio 3" },
      { url: "https://tu-servidor.com/dino/s1e3.mp4", title: "Episodio 3" },
      { url: "https://tu-servidor.com/dino/s1e3.mp4", title: "Episodio 3" },
      { url: "https://tu-servidor.com/dino/s1e3.mp4", title: "Episodio 3" },
      { url: "https://tu-servidor.com/dino/s1e3.mp4", title: "Episodio 3" },
      { url: "https://tu-servidor.com/dino/s1e3.mp4", title: "Episodio 3" },
      { url: "https://tu-servidor.com/dino/s1e3.mp4", title: "Episodio 3" },
      { url: "https://tu-servidor.com/dino/s1e3.mp4", title: "Episodio 3" },
      { url: "https://tu-servidor.com/dino/s1e3.mp4", title: "Episodio 3" },
      { url: "https://tu-servidor.com/dino/s1e3.mp4", title: "Episodio 3" },
      { url: "https://tu-servidor.com/dino/s1e3.mp4", title: "Episodio 3" },
      { url: "https://tu-servidor.com/dino/s1e3.mp4", title: "Episodio 3" },
      { url: "https://tu-servidor.com/dino/s1e3.mp4", title: "Episodio 3" }
    ],
    "Temporada 2": [
      { id: "OH57rtnKCEM", title: "Episodio 1" },
      { id: "WpA23XqUnq0", title: "Episodio 2" },
      { id: "Sc-RYjjOtNQ", title: "Episodio 3" }
    ]
    }
};
