// SimpsonsTV.js
const listaSimpsons = [
    { "nombre": "T1 E1", "url": "https://vidhidevip.com/embed/oc3f1hrpzz2t" },
    { "nombre": "T1 E2", "url": "" },
    { "nombre": "T1 E3", "url": "" },
    { "nombre": "T1 E4", "url": "" },
    { "nombre": "T1 E5", "url": "" },
    { "nombre": "T1 E6", "url": "" },
    { "nombre": "T1 E7", "url": "" },
    { "nombre": "T1 E8", "url": "" },
    { "nombre": "T1 E9", "url": "" },
    { "nombre": "T1 E10", "url": "" },
    { "nombre": "T1 E11", "url": "" },
    { "nombre": "T1 E12", "url": "" },
    { "nombre": "T1 E13", "url": "" },
    { "nombre": "T2 E1", "url": "" },
    { "nombre": "E15", "url": "" },
    { "nombre": "E16 -", "url": "" },
    { "nombre": "E17 -", "url": "" },
    { "nombre": "E18 -", "url": "" },
    { "nombre": "E19 -", "url": "" },
    { "nombre": "E20 -", "url": "" },
    { "nombre": "E21 -", "url": "" },
    { "nombre": "E22 -", "url": "" },
    // Agregá todos los que quieras aquí...
];
